apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-auth
  namespace: keycloak-system

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: dive-keycloak
                port:
                  number: 80
